export enum Permission {
  ALL = "ALL",
  UNIVERSITY_PROGRAMS = "UNIVERSITY_PROGRAMS",
  FREE_COURSE = "FREE_COURSE",
  PROFESSIONAL_COURSE = "PROFESSIONAL_COURSE",
  SCHOLARSHIP = "SCHOLARSHIP",
  GRANTS = "GRANTS",
  FELLOWSHIP = "FELLOWSHIP",
  JOBS = "JOBS",
  CAREER_CATALOGUE = "CAREER_CATALOGUE",
  EVENTS = "EVENTS",
}